author: Guanyu He
github_url: https://github.com/heguanyu/TestGithubCI
output: jazzydocs
swift_build_tool: xcodebuild
theme: apple
#module: TestXCFramework
build_tool_arguments:
  - -resolvePackageDependencies
  - -workspace
  - TestGithubCI.xcworkspace
  - -scheme
  - TestXCFramework
  - -sdk
  - iphoneos