# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

podspecPath = "TestGithubCI.podspec"

platform :ios do
  # before_all do
  #   begin
  #     xcversion(version: "~> 13.2")
  #   rescue => ex
  #     UI.error("Failed when switching to Xcode version: #{ex}")
  #   end
  # end

  desc "Pulls dependencies"
  lane :build_dependencies do
    cocoapods
  end

  desc "Generate Apple doc"
  lane :gen_apple_doc do
    #generate doc
    # appledoc(
    #   project_name: "TestGithubCI",
    #   project_company: "LinkedIn, Inc",
    #   input: [
    #     "TestXCFramework"
    #   ],
    #   options: "--keep-intermediate-files --search-undocumented-doc",
    #   warnings: "--warn-missing-output-path --warn-missing-company-id"
    # )
    system "rm -r ../derived_data/*"
    jazzy(
      config: '.jazzy.yaml'
    )
    # commit and push to the doc branch
    git_commit(
      path: './docs',
      message: "Updated docs"
    )
    push_to_git_remote(
      remote: 'origin',
      remote_branch: 'gh-pages',
      force: true
    )
  end

  lane :lints do
    sh "pwd"
    subdirs = ["TestXCFramework", "TestXCFrameworkTests"]
    files = []
    Dir.chdir("..") do
      files = subdirs.map { |dir| Dir.glob("#{dir}/**/*.swift")}.flatten(1)
    end
    swiftlint(
      mode: :lint,
      files: files,
      executable: "Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml"
    )
  end

  lane :tests do
    scan(
      scheme: "TestGithubCI",
      derived_data_path: "derived_data"
    )
    system "rm -r ../xcov_output/*"
    xcov(
      workspace: "TestGithubCI.xcworkspace",
      scheme: "TestGithubCI",
      output_directory: "xcov_output",
      skip_slack: true,
      derived_data_path: "derived_data"
    )
#    pod_lib_lint
  end

  desc "Push version to cocoapods"
  lane :push_cocoapods do |options|

    target_version = options[:version]
    raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?

    newVersion = version_bump_podspec(
      path: podspecPath,
      bump_type: "patch"
    )
    git_commit(
      path: podspecPath,
      message: "Version bump to #{newVersion}"
    )
    # push_to_git_remote
    # sh("git", "push", ENV["GITHUB_TOKEN"]+"@github.com/heguanyu/TestGithubCI.git")
    add_git_tag(tag: newVersion)
    push_git_tags
    # pod_push(allow_warnings: true)
  end

  lane :someA do |options|
    puts "Hello world!"
  end

  desc "Create a release based on change log"
  lane :create_release do |options|
    target_version = options[:version]
    build_path = "build"
    changelog_filename = "CHANGELOG.md"

    # Prepare the binaries and release note
    binary_frameworks = xcframework(version: target_version)
    release_content = read_changelog(
      section_identifier: '[Unreleased]',	# Specify what section to read
      excluded_markdown_elements: ['-', '###']
    )

    # stamp the new version into change log and check-in
    stamp_changelog(
      section_identifier: target_version,
      git_tag: target_version,
      should_stamp_date: true,
      stamp_datetime_format: '%FT%TZ'
    )
    git_commit(
      path: ["./CHANGELOG.md"],
      message: "Version bump to #{target_version}",
      allow_nothing_to_commit: true
    )
    # push_to_git_remote
    sh("git", "push", "https://"+ENV["GITHUB_TOKEN"]+"@github.com/heguanyu/TestGithubCI.git")
    add_git_tag(tag: target_version)
    # push_git_tags
    sh("git", "push", "https://"+ENV["GITHUB_TOKEN"]+"@github.com/heguanyu/TestGithubCI.git", "origin", "--tags")

    set_github_release(
      repository_name: "heguanyu/TestGithubCI",
      api_token: ENV["RELEASE_TOKEN"],
      name: target_version,
      tag_name: target_version,
      upload_assets: binary_frameworks,
      description: release_content
    )
    # pod_push(allow_warnings: true)
  end

  desc "Create binary frameworks with the `xcframework` format under the `build/` folder."
  lane :xcframework do |options|
    target_version = options[:version]
    output_path = "build"

    FileUtils.rm_rf "../#{output_path}"

    artifact_paths = [
      build_xcframework(version: target_version, scheme: "TestXCFramework", output: output_path)
    ]

    zipped_files = []
    artifact_paths.each do |path|
      zipped_files << zip(path: path)
    end
    zipped_files
  end
end


