# This workflow triggers pod push

name: Post Deployment

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - main


jobs:
  post-deployment:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'
      # Send release as attachment is in destination repo
      - name: Goto main repo and pod push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          fastlane publishToCocoapod