# This workflow generates document and push to gh-pages

name: Post Deployment

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - main

  # Normally should be called by another workflow
  workflow_call:

jobs:
  post-deployment:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # Generate document
      - name: Create apple doc
        run: |
          bundle install
          fastlane build_dependencies
          fastlane gen_apple_doc