# This workflow triggers pod push

name: Post Deployment

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - main


jobs:
  post-deployment:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      # Send release as attachment is in destination repo
      - name: Goto main repo and pod push
        run: |
          cd main
          fastlane publishToCocoapod