name: Release

on:
  # This job should only be manually triggered
  workflow_dispatch:

jobs:
  # Do validation
  do-validation:
    uses: heguanyu/TestGithubCI/.github/workflows/validation.yml@main

  # Then proceed with release
  release:
    runs-on: macOS-latest
      # This deal with version bump and push to cocoapods
      - name: Build and publish to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run:
          fastlane push_cocoapods