name: Release

on:
  # This job should only be manually triggered
  workflow_dispatch:
    branches:
      - main
    inputs:
      release-message:
        required: true
        description: Release note
jobs:
  # Do validation
  do_validation:
    uses: heguanyu/TestGithubCI/.github/workflows/validation.yml@main

  # Then proceed with release
  release:
    needs: do_validation
    runs-on: macOS-latest
      # This deal with version bump and push to cocoapods
    steps:
      # Checks-out to repo
      - uses: actions/checkout@v2
      - name: Build and publish to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle install
          fastlane build_dependencies
          fastlane run xcbuild scheme:"TestXCFramework"
          fastlane push_cocoapods

  post_release:
    needs: release
    uses: heguanyu/TestGithubCI/.github/workflows/post-release.yml@main
