# This workflow generates document and push to gh-pages

name: Release to public repo

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - '*'
    inputs:
      release_version:
        required: true
        description: Release version

env:
  repo_user: heguanyu
  destination_path: TestPoCIntegration

jobs:
  create-doc-and-push-to-another-repo:
    runs-on: macOS-latest
    steps:
      # Checkout both repos
      - uses: actions/checkout@v3
        with:
          path: main
          fetch-depth: 0
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
          repository: ${{env.repo_user}}/${{env.destination_path}}
          path: ${{env.destination_path}}
          token: ${{secrets.RELEASE_TOKEN}}
      - uses: actions/setup-node@v3
      # Generate document
      - name: Create the docs directory from webui
        run: |
          cd main
          bundle install
          fastlane build_dependencies
          fastlane gen_web_ui_to_docs
      # Release on self repo
      - name: build-and-release-on-main-repo
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          cd main
          fastlane create_release version:${{github.event.inputs.release_version}} shadow_repo:${{env.repo_user}}/${{env.destination_path}}

      # Copy docs to the destination repo
      - name: Copy doc to destination
        run: |
          rm -rf ${{env.destination_path}}/binaries/${{github.event.inputs.release_version}}
          mkdir -p ${{env.destination_path}}/binaries/${{github.event.inputs.release_version}}
          cp -r main/build/TestXCFramework-${{github.event.inputs.release_version}}/TestXCFramework.xcframework.zip ${{env.destination_path}}/binaries/${{github.event.inputs.release_version}}
          
          rm -rf ${{env.destination_path}}/docs
          mkdir -p ${{env.destination_path}}/docs
          cp -r main/docs/* ${{env.destination_path}}/docs/
          
          rm -rf ${{env.destination_path}}/doc_archives/${{github.event.inputs.release_version}}
          mkdir -p ${{env.destination_path}}/doc_archives/${{github.event.inputs.release_version}}
          cp -r main/jazzydocs/* ${{env.destination_path}}/doc_archives/${{github.event.inputs.release_version}}/

      # Checkin the docs to destination remote
      - name: Goto the dest repo and commit
        run: |
          cd ${{env.destination_path}}
          pwd
          git add --force docs
          git add binaries/${{github.event.inputs.release_version}}/TestXCFramework.xcframework.zip
          ls -al doc_archives/${{github.event.inputs.release_version}}/
          git add --force docs_archives/${{github.event.inputs.release_version}}
          git commit -a -m "Update the docs and the framework"
          git push origin main

