name: Release

on:
  # This job should only be manually triggered
  workflow_dispatch:
    branches:
      - main
    inputs:
      release_version:
        required: true
        description: Release version
jobs:
  # Do validation
#  do_validation:
#    uses: heguanyu/TestGithubCI/.github/workflows/validation.yml@main

  # Then proceed with release
  release:
#    needs: do_validation
    runs-on: macOS-latest
      # This deal with version bump and push to cocoapods
    steps:
      # Checks-out to repo
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Build and publish to cocoapods
        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          bundle install
          fastlane build_dependencies
          fastlane create_release version:${{github.event.inputs.release_version}}

#  post_release:
#    needs: release
#    uses: heguanyu/TestGithubCI/.github/workflows/post-release.yml@main
