name: Release

on:
  # This job should only be manually triggered
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: macOS-latest
      # This deal with version bump and push to cocoapods
    steps:
      # Checks-out to repo
      - uses: heguanyu/TestGithubCI/.github/workflows/validation.yml@main
      - name: Build and publish to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle install
          fastlane push_cocoapods