# This workflow generates document and push to gh-pages

name: Release to public repo

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    # Whenever a new tag is created, run this post-release workflow    /

env:
  repo_user: heguanyu
  destination_path: TestPoCIntegration

jobs:
  create-doc-and-push-to-another-repo:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
          fetch-depth: 0
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
          repository: ${{env.repo_user}}/${{env.destination_path}}
          path: ${{env.destination_path}}
          token: ${{secrets.RELEASE_TOKEN}}
      - uses: actions/setup-node@v3
      - name: Install sourcekitten
        run: |
          brew install sourcekitten
          cd main
          sourcekitten doc --module-name TestGithubCI -- -resolvePackageDependencies -workspace TestGithubCI.xcworkspace -scheme TestXCFramework -sdk iphoneos
      # Generate document
      - name: Create the docs directory from webui
        run: |
          cd main
          bundle install
          fastlane build_dependencies
          fastlane gen_web_ui_to_docs
      - name: Copy doc to destination
        run: |
          rm -r ${{env.destination_path}}/docs
          mkdir -p ${{env.destination_path}}/docs
          cp -r main/docs/* ${{env.destination_path}}/docs/
      - name: Goto the dest repo and commit
        run: |
          cd ${{env.destination_path}}
          pwd
          git add --force docs
          git commit -a -m "Update the docs"
          git push origin main