# This workflow generates document and push to gh-pages

name: Release to public repo

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    # Whenever a new tag is created, run this post-release workflow
    tags:
      - '*'           # Push events to every tags


jobs:
  create-doc-and-push-to-another-repo:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
            repository: heguanyu/TestPoCIntegration
            path: TestPoCIntegration
            token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
      # Generate document
      - name: Create the docs directory from webui
        run: |
          bundle install
          fastlane build_dependencies
          fastlane gen_web_ui_to_docs
      - name: Copy doc to destination
        run: |
          mkdir -p TestPoCIntegration/docs
          cp -r main/docs/* TestPoCIntegration/docs/
      - name: Goto the dest repo and commit
        run: |
          cd TestPoCIntegration
          pwd
          git add --force docs
          git commit -a -m "Update the docs"
          git push origin main