# This is a basic workflow to help you get started with Actions

name: Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for all branches
#  push:
#    branches:
#      - '*'

  # Can be triggered from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validation:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out to repo
      - uses: actions/checkout@v2

      # Use xcode 14
      - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'

      # Install bundle and dependencies
      - name: preparations
        run: |
          bundle install
          fastlane build_dependencies

      # Unit tests
      - name: lints, unit tests and coverage report
        run: |
          fastlane lints
          fastlane tests